[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/r/*"
  to = "/.netlify/functions/redirect"
  status = 200

# API endpoint'i
[[redirects]]
  from = "/api/shorten"
  to = "/.netlify/functions/shorten"
  status = 200

# Mevcut siten i√ßin
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
